# Netlify configuration for NextAuth & Prisma in serverless environment

[build]
  command = "pnpm config set enable-pre-post-scripts true && pnpm install --no-frozen-lockfile && pnpm prisma generate && pnpm build"
  publish = ".next"

[build.environment]
  # Increase Node memory to accommodate Next.js 15.x builds
  NODE_OPTIONS = "--max_old_space_size=4096"
  # Enable Prisma query logging for debugging
  DEBUG = "prisma:*"
  # Add logging for NextAuth (optional, remove in production)
  NEXTAUTH_DEBUG = "true"
  # Force using Edge runtime for API routes when possible
  NEXT_RUNTIME = "edge"
  # Set Node and PNPM versions
  NODE_VERSION = "20.11.1"
  PNPM_VERSION = "10.11.0"

[dev]
  command = "pnpm dev"
  port = 3000
  # Increase framework timeout for development with large operations
  framework_timeout = 60000

[functions]
  # Functions configuration for Netlify serverless
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Include Prisma in external modules to prevent packaging issues
  external_node_modules = [
    "@prisma/client", 
    "@prisma/engines", 
    "next-auth"
  ]
  # Ensure Prisma schema and migration files are included in the function bundle
  included_files = [
    "**/*.prisma",
    "prisma/migrations/**/*", 
    "prisma/schema.prisma"
  ]
  # Set appropriate timeouts for cold starts with database connections
  timeout = 30

# Handle database connections better in serverless environment
[functions.database]
  # Keep connection pool small to prevent resource exhaustion
  pool_limit = 5
  # Shorter idle timeout for better resource management
  idle_timeout = 120

# Edge functions configuration - better for Next.js API routes
[edge_functions]
  # Opt to use edge functions when possible for faster response times
  use_edge_when_possible = true

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Enable Edge middleware processing
    enable_middleware = true
    # Setup SSR fallback for performance
    use_edge_functions = true

# Redirect configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Keep the database connection warm with regular pings
[[plugins]]
  package = "@netlify/plugin-functions-scheduled-event"
  [plugins.inputs]
    # Ping the database every 5 minutes to prevent cold starts
    schedule = "0/5 * * * *"
    command = "curl -s -o /dev/null -w '%{http_code}' $DEPLOY_URL/api/ping"
