[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = ".next"  # Default Next.js output directory

[dev]
  command = "pnpm dev"
  port = 3000

[functions]
  directory = "netlify/functions"  # Optional, adjust if used

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "22.15.1"
  PNPM_VERSION = "10.11.0"
