# Netlify configuration file
[build]
  # Directory with the built site (Next.js default output directory)
  publish = ".next"
  # The build command
  command = "npm run build"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Deployment settings
[build.environment]
  NODE_VERSION = "18"
  # Increase memory limit for builds
  NODE_OPTIONS = "--max_old_space_size=4096"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://api.supabase.co;"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings
[functions]
  # Directory with serverless functions
  directory = "netlify/functions"
  # Increase timeout for functions
  node_bundler = "esbuild"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Edge functions configuration - CORRECT FORMAT
# The error was in this section, using [edge_functions] instead of [[edge_functions]]
# Each edge function needs its own [[edge_functions]] section

# If you want to use edge functions, uncomment and properly configure:
# [[edge_functions]]
# path = "/api/auth/*"
# function = "auth"

# [[edge_functions]]
# path = "/api/feedback"
# function = "feedback"

# Enable Next.js Image Optimization on Netlify
[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
