# Netlify configuration file for Next.js application
[build]
  # Simplified build command using setup-build.js
  command = "node setup-build.js && PYTHON_VERSION=3.9.7 USE_IDIOMATIC_VERSION_FILES=true pnpm install --no-frozen-lockfile && PRISMA_BINARY_PLATFORM=debian-openssl-3.0.x PRISMA_SCHEMA_PATH=/opt/build/repo/schema.prisma pnpm prisma:generate && pnpm build"
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
[build.environment]
  NODE_VERSION = "18.20.0"
  PYTHON_VERSION = "3.9.7"
  PNPM_VERSION = "10.11.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  DEBUG = "prisma*,next*,auth*,pnpm*"
  NEXT_RUNTIME = "nodejs"
  NEXT_DISABLE_STATICPRERENDERS = "true"
  PRISMA_CLI_BINARY_TARGETS = "debian-openssl-3.0.x,linux-musl-openssl-3.0.x"
  PRISMA_CLIENT_ENGINE_TYPE = "library"
  PRISMA_BINARY_PLATFORM = "debian-openssl-3.0.x"
  PRISMA_ENGINES_MIRROR = "https://binaries.prisma.sh"
  PRISMA_SCHEMA_PATH = "/opt/build/repo/schema.prisma"
  NODE_ENV = "production"
  # Add missing module flags
  PNPM_INSTALL_FLAGS = "--shamefully-hoist"
  NEXT_DEBUG = "true"
  # Explicitly enable idiomatic version files
  USE_IDIOMATIC_VERSION_FILES = "true"
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines", "prisma"]
  included_files = [
    "node_modules/.prisma/**/*",
    "node_modules/@prisma/client/**/*", 
    "prisma/**/*",
    ".env",
    ".env.production",
    "schema.prisma",
    ".python-version"
  ]
[build.processing]
  skip_processing = false
[build.processing.images]
  compress = true
[build.cache]
  functions = false
  pages = false
  fallback_error = true
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://api.supabase.co;"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"/.netlify/functions/report-csp-violations\"}]}"
[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
