# Netlify configuration file for Next.js application
[build]
  command = "node prisma-setup.js && mise settings add idiomatic_version_file_enable_tools node || true && MISE_DISABLE=1 pnpm install --no-frozen-lockfile && cp -f prisma/schema.prisma schema.prisma && PRISMA_BINARY_PLATFORM=debian-openssl-3.0.x PRISMA_SCHEMA_PATH=./prisma/schema.prisma NODE_ENV=production pnpm prisma generate && NODE_OPTIONS='--max_old_space_size=4096' pnpm build"
  publish = ".next"
  clean = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.0"
  PNPM_VERSION = "10.11.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  PRISMA_BINARY_PLATFORM = "debian-openssl-3.0.x"
  PRISMA_SCHEMA_PATH = "./prisma/schema.prisma"
  PRISMA_CLI_BINARY_TARGETS = "debian-openssl-3.0.x,linux-musl-openssl-3.0.x"
  PRISMA_CLIENT_ENGINE_TYPE = "library"
  PRISMA_ENGINES_MIRROR = "https://binaries.prisma.sh"
  NODE_ENV = "production"
  MISE_DISABLE = "1"
  NETLIFY_CACHE_NODE_MODULES = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
  included_files = [
    "node_modules/.prisma/**/*",
    "node_modules/@prisma/client/**/*",
    "node_modules/prisma/**/*",
    "prisma/**/*",
    "prisma/schema.prisma",
    "schema.prisma",
    ".env",
    ".env.production"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
