[build]
  command = "pnpm config set enable-pre-post-scripts true && pnpm install --no-frozen-lockfile && pnpm prisma generate && pnpm build"
  publish = ".next"

[dev]
  command = "pnpm dev"
  port = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "20.11.1"
  PNPM_VERSION = "10.11.0"
